version: "3.8"

services:
  pg:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - partkaru_node_data:/bitnami/postgresql

volumes:
  partkaru_node_data:
