@baseUrl = http://localhost:3333

# @name create_brand
POST {{baseUrl}}/brands
Content-Type: application/json

{
  "name": "Ford",
  "popular": false,
  "countryOrigin": "USA"
}

###

# @name get_all_brands
Get {{baseUrl}}/brands